# OpenAPI Specification TEMPLATE for a Dynamic Tariff Price API.
# Based on the VSE standard https://www.strom.ch/de/shop/dynamische-netznutzungstarife-im-verteilnetz-hdn-ch-2025.
# This template contains the essential endpoints and schemas.
#
# Provided by SmartGridready: https://smartgridready.ch/loesungen/dynamischetarife
# Author: Matthias Krebs
#
# Version 2.0.0 (WORK IN PROGRESS)
#

openapi: 3.0.3
info:
  title: Dynamic Tariff Retrieval API
  description: |
    API to retrieve dynamic tariff prices of an electricity provider.
    Follows the VSE standard https://www.strom.ch/de/shop/dynamische-netznutzungstarife-im-verteilnetz-hdn-ch-2025.
  version: '2.0.0'
servers:
  # TODO: Replace this with your actual API URL - endpoint paths will be relative to this URL
  - url: https://tariffs.example.org/api/v2
    description: Example server
paths:
  /tariffs:
    get:
      summary: Retrieve dynamic tariff prices
      description: |
        This endpoint retrieves dynamic tariff prices in a given time period.
        The endpoint is public and requires no authentication.
      operationId: get-tariffs
      tags:
        - public
      parameters:
        - name: tariff_type
          in: query
          description: Filters by tariff type. If omitted, all available tariff types are returned.
          schema:
            $ref: '#/components/schemas/TariffType'
        - name: tariff_name
          in: query
          description: Filters by a specific tariff product of the provider. If omitted, the provider's default tariff is returned.
          schema:
            $ref: '#/components/schemas/TariffName'
        - name: start_timestamp
          in: query
          description: |
            Marks the begin of the price retrieval period. If omitted, the begin of the current day is utilized.
            The `start_timestamp` of the first returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-01T00:00:00+01:00'
        - name: end_timestamp
          in: query
          description: |
            Marks the end of the price retrieval period. If omitted, the begin of the following day is utilized.
            The `end_timestamp` of the last returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-02T00:00:00+01:00'
      responses:
        '200':
          description: Dynamic tariff prices retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffResponse'
              example:
                publication_timestamp: '2026-01-31T18:00:00+01:00'
                prices:
                  - start_timestamp: '2026-02-01T00:00:00+01:00'
                    end_timestamp: '2026-02-01T00:15:00+01:00'
                    electricity:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.121
                    grid:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.113
                      - component: base
                        unit: CHF/m
                        value: 5
                    integrated:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.234
                      - component: base
                        unit: CHF/m
                        value: 5
                  - start_timestamp: '2026-02-01T00:15:00+01:00'
                    end_timestamp: '2026-02-01T00:30:00+01:00'
                    electricity:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.123
                    grid:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.102
                      - component: base
                        unit: CHF/m
                        value: 5
                    integrated:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.225
                      - component: base
                        unit: CHF/m
                        value: 5
        '400':
          description: Incorrect query parameters were given.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid tariff_name 'xyz'. Allowed values: 'example_tariff'."
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: An internal error occurred.
      security:
        - {}
  /customerTariffs:
    get:
      summary: Retrieve dynamic tariff prices
      description: |
        This endpoint retrieves dynamic tariff prices in a given time period.
        The endpoint is protected.
      operationId: get-customer-tariffs
      tags:
        - protected
      parameters:
        - name: ems_instance_id
          in: query
          required: true
          description: |
            EMS installation/serial identifier; used to identify the EMS instance and its binding to a metering point
          schema:
            type: string
            maxLength: 128
        - name: tariff_type
          in: query
          description: Filters by tariff type. If omitted, all available tariff types are returned.
          schema:
            $ref: '#/components/schemas/TariffType'
        - name: start_timestamp
          in: query
          description: |
            Marks the begin of the price retrieval period. If omitted, the begin of the current day is utilized.
            The `start_timestamp` of the first returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-01T00:00:00+01:00'
        - name: end_timestamp
          in: query
          description: |
            Marks the end of the price retrieval period. If omitted, the begin of the following day is utilized.
            The `end_timestamp` of the last returned interval should match this parameter.
          schema:
            $ref: '#/components/schemas/TimeStamp'
          example: '2026-01-02T00:00:00+01:00'
      responses:
        '200':
          description: Dynamic tariff prices retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TariffResponse'
              example:
                publication_timestamp: '2026-01-31T18:00:00+01:00'
                prices:
                  - start_timestamp: '2026-02-01T00:00:00+01:00'
                    end_timestamp: '2026-02-01T00:15:00+01:00'
                    electricity:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.121
                    grid:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.113
                      - component: base
                        unit: CHF/m
                        value: 5
                    integrated:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.234
                      - component: base
                        unit: CHF/m
                        value: 5
                  - start_timestamp: '2026-02-01T00:15:00+01:00'
                    end_timestamp: '2026-02-01T00:30:00+01:00'
                    electricity:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.123
                    grid:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.102
                      - component: base
                        unit: CHF/m
                        value: 5
                    integrated:
                      - component: energy
                        unit: CHF/kWh
                        value: 0.225
                      - component: base
                        unit: CHF/m
                        value: 5
        '400':
          description: Incorrect query parameters were given.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid tariff_name 'xyz'. Allowed values: 'example_tariff'."
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Unauthorized.
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: EMS not linked to your account.
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: An internal error occurred.
      security:
        - OAuthPKCE: [openid, offline]
components:
  schemas:
    PriceArray:
      type: array
      items:
        $ref: '#/components/schemas/PriceItem'
      description: Contains the prices for the requested time intervals.
    PriceItem:
      type: object
      required:
        - start_timestamp
        - end_timestamp
      properties:
        start_timestamp:
          $ref: '#/components/schemas/TimeStamp'
        end_timestamp:
          $ref: '#/components/schemas/TimeStamp'
      anyOf:
        - properties:
            electricity:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            grid:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            integrated:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            regional_fees:
              $ref: '#/components/schemas/PriceComponentArray'
        - properties:
            feed_in:
              $ref: '#/components/schemas/PriceComponentArray'
      description: A price item of a time interval, contains tariff components.
    PriceComponentArray:
      type: array
      items:
        $ref: '#/components/schemas/PriceComponentItem'
      description: Price components of a tariff component.
    PriceComponentItem:
      type: object
      required:
        - component
        - unit
        - value
      properties:
        component:
          $ref: '#/components/schemas/PriceComponent'
        unit:
          $ref: '#/components/schemas/PriceUnit'
        value:
          $ref: '#/components/schemas/PriceValue'
      additionalProperties: true
    TariffName:
      type: string
      enum:
      # TODO: Define your actual tariff product names here, since they are provider-specific
        - example_tariff
      description: |
        Tariff names specified by DSO
          * `example_tariff` - An example tariff
    TariffType:
      type: string
      enum:
        - electricity
        - grid
        - metering
        - national_fees
        - regional_fees
        - integrated
        - feed_in
        - refund
      description: |
        Tariff types (tariff components) specified by VSE
          * `electricity` - Electricity energy supply to end consumers
          * `grid` - Grid usage (distribution and transmission networks) including general and individual system services, grid surcharge according to Art. 35 EnG + electricity reserve + socialized costs via the transmission grid
          * `metering` - Metering infrastructure fees
          * `national_fees` - National surcharges (e.g. Swissgrid)
          * `regional_fees` - Local or regional surcharges (e.g. concession fees)
          * `dso` - Combination of `grid`, `metering` and `national_fees`
          * `integrated` - Combination of `electricity` and `dso`
          * `feed_in` - Compensation for feed-in into grid (positive value means reimbursement of customer)
          * `refund` - Refund for grid supportive storage operation
    PriceUnit:
      type: string
      enum:
        - CHF/kWh
        - CHF/kVarh
        - CHF/y
        - CHF/m
        - CHF/w
        - CHF/d
        - CHF/12h
        - CHF/6h
        - CHF/4h
        - CHF/2h
        - CHF/1h
        - CHF/30min
        - CHF/15min
        - CHF/kW/y
        - CHF/kW/m
        - CHF/kW/w
        - CHF/kW/d
        - CHF/kW/12h
        - CHF/kW/6h
        - CHF/kW/4h
        - CHF/kW/2h
        - CHF/kW/1h
        - CHF/kW/30min
        - CHF/kW/15min
      description: |
        Price unit:
          * `CHF/kWh` - CHF per kWh
          * `CHF/kVarh` - CHF per kVarh
          * `CHF/y` - CHF per year
          * `CHF/m` - CHF per month
          * `CHF/w` - CHF per week
          * `CHF/d` - CHF per day
          * `CHF/12h` - CHF per 12 hours
          * `CHF/6h` - CHF per 6 hours
          * `CHF/4h` - CHF per 4 hours
          * `CHF/2h` - CHF per 2 hours
          * `CHF/1h` - CHF per hour
          * `CHF/30min` - CHF per 30 minutes
          * `CHF/15min` - CHF per 15 minutes
          * `CHF/kW/y` - CHF per kW per year
          * `CHF/kW/m` - CHF per kW per month
          * `CHF/kW/w` - CHF per kW per week
          * `CHF/kW/d` - CHF per kW per day
          * `CHF/kW/12h` - CHF per kW per 12 hours
          * `CHF/kW/6h` - CHF per kW per 6 hours
          * `CHF/kW/4h` - CHF per kW per 4 hours
          * `CHF/kW/2h` - CHF per kW per 2 hours
          * `CHF/kW/1h` - CHF per kW per hour
          * `CHF/kW/30min` - CHF per kW per 30 minutes
          * `CHF/kW/15min` - CHF per kW per 15 minutes
    PriceValue:
      type: number
      format: decimal
      description: A numeric price value.
    PriceComponent:
      type: string
      enum:
        - base
        - energy
        - power
        - reactive_power
      description: |
        Price components:
        * `base` - Base tariff
        * `energy` - Energy
        * `power` - Active power
        * `reactive_power` - Reactive power
    TimeStamp:
      type: string
      anyOf:
        - format: date-time
        - format: empty
      description: An ISO-8601 time stamp with time zone offset.
      example: '2026-05-23T13:30:00+02:00'
    TariffResponse:
      type: object
      required:
        - publication_timestamp
        - prices
      properties:
        publication_timestamp:
          $ref: '#/components/schemas/TimeStamp'
        prices:
          $ref: '#/components/schemas/PriceArray'
      additionalProperties: true
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: The error message.
  securitySchemes:
    OAuthPKCE:
      type: oauth2
      description: OAuth with PKCE
      flows:
        authorizationCode:
          # TODO: Replace this with your actual OAuth server URL, may be different from API server
          authorizationUrl: https://tariffs.example.org/oauth2/authorize
          tokenUrl: https://tariffs.example.org/oauth2/token
          refreshUrl: https://tariffs.example.org/oauth2/token
          scopes:
            openid: minimal
            offline: refresh token
