name: Push changed files to SGr server
run-name: ${{ github.actor }} is pushing changed files to SGr server 🚀
on:
  push:
    branches:
      - 'master'
jobs:
  upload:
    runs-on: ubuntu-latest
    name: Push uploaded files to SGr server
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
      
    - name: Get changed files
      uses: tj-actions/changed-files@v35
      id: changed-files
      
    - name: push changed files via curl to SGrWebApp
      env:
        SGR_WEB_APP_TOKEN: ${{ secrets.SGR_WEB_APP_TOKEN }}
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
          echo "detected changed file: $file"
        done
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "try to upload added $file"
          curl --upload-file "$file" "https://library.smartgridready.ch/$file?add&token=$SGR_WEB_APP_TOKEN"
        done
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          echo "try to upload modified $file"
          curl --upload-file "$file" "https://library.smartgridready.ch/$file?update&token=$SGR_WEB_APP_TOKEN"
        done
        for file in ${{ steps.changed-files.deleted_files }}; do
          echo "try to upload deleted $file"
          curl --upload-file "$file" "https://library.smartgridready.ch/$file?delete&token=$SGR_WEB_APP_TOKEN"
        done
        for file in ${{ steps.changed-files.renamed_files }}; do
          echo "try to upload renamed $file"
          # curl --silent --upload-file "$file" "https://library.smartgridready.ch/$file?rename&token=$SGR_WEB_APP_TOKEN"
        done
        for file in ${{ steps.changed-files.all_old_new_renamed_files }}; do
          echo "try to upload renamed (old/new) $file"
          # curl --silent --upload-file "$file" "https://library.smartgridready.ch/$file?rename&token=$SGR_WEB_APP_TOKEN"
        done
