name: Push changed files to SGr server
run-name: ${{ github.actor }} is pushing changed files to SGr server 🚀
on:
  push:
    branches: [ master ]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with:
        fetch-depth: 0
    - name: Changed Files
      uses: tj-actions/changed-files@v35.7.1
      id: changed-files
    - name: curl
      env:
        SGR_WEB_APP_TOKEN: ${{ secrets.SGR_WEB_APP_TOKEN }}
      run: |
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "try to upload added $file"
          curl --silent --upload-file "$file" https://library.smartgridready.ch/$file?add&$token=$SGR_WEB_APP_TOKEN
        done
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          echo "try to upload modified $file"
          curl --silent --upload-file "$file" https://library.smartgridready.ch/$file?update$token=$SGR_WEB_APP_TOKEN
        done
        for file in ${{ steps.changed-files.deleted_files }}; do
          echo "try to upload deleted $file"
          curl --silent --upload-file "$file" https://library.smartgridready.ch/$file?delete$token=$SGR_WEB_APP_TOKEN
        done
        for file in ${{ steps.changed-files.renamed_files }}; do
          echo "try to upload renamed $file"
          # curl --silent --upload-file "$file" https://library.smartgridready.ch/$file?rename$token=$SGR_WEB_APP_TOKEN
        done
        for file in ${{ steps.changed-files.all_old_new_renamed_files }}; do
          echo "try to upload renamed (old/new) $file"
          # curl --silent --upload-file "$file" https://library.smartgridready.ch/$file?rename$token=$SGR_WEB_APP_TOKEN
        done
