name: Push changed files to SGr server
run-name: ${{ github.actor }} is pushing changed files to SGr server 🚀
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - name: curl
      run: |
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "try to upload added $file"
          curl --upload-file "$file" https://library.smartgridready.ch/$file?add || true
        done
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          echo "try to upload modified $file"
          curl --upload-file "$file" https://library.smartgridready.ch/$file?update || true
        done
        for file in ${{ steps.changed-files.deleted_files }}; do
          echo "try to upload deleted $file"
          curl --upload-file "$file" https://library.smartgridready.ch/$file?delete || true
        done
